### ISSUE TITLE
Replace dist/ w/ prepublish script

### ISSUE THREAD

**Issue by sethfitz** [americanpanorama/panorama#11]
This will allow downstream consumers to `require()` the toolkit from GitHub and get an up-to-date bundle w/o it being including in the repository.

However, in order to build assets, `devDependencies` need to be installed, so the first step is probably to recursively call `npm install` to make them available. (The other alternative is to turn them into `dependencies`, but that substantially increases the footprint when npm-style module resolution is used.)

**Comment by ericsoco** [comment]
Ah, good idea. Will a single `npm install` (this will be subsequent to the initial `npm install` run when building the project initially) always work to pull in `peerDependencies`?

**Comment by sethfitz** [comment]
No, I don't think so.

**Comment by ericsoco** [comment]
Also implemented in [our fork](https://github.com/stamen/panorama/blob/master/_build-config/publish-module.sh#L26-L27).
